import React from "react";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Head from "next/head";

const Layout = ({ children, metaTitle, metaDescription }) => {
  return (
    <>
      <div>
        <Head>
          <title>{`Create Next App - ${metaTitle}`}</title>
          <meta
            name="description"
            content={metaDescription || "Generated by create next app"}
          />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
          <Header />
          {children}
          <Footer />
        </div>
      </div>
    </>
  );
};

export default Layout;
